# Generated by Django 2.1.1 on 2018-10-14 20:36

import collectibles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcquiredItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('acquired',),
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=50)),
                ('content_type', models.CharField(choices=[('URL', 'Url content'), ('YT', 'Youtube video'), ('IMG', 'Image'), ('INFO', 'Information'), ('API', 'Rest API Call')], max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(max_length=124, null=True)),
                ('icon_path', models.CharField(default='img/stickers/default.png', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('QR_key', models.CharField(default=collectibles.models.key_generator, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=124)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('img_path', models.CharField(default='img/locations/default.jpg', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('nick', models.CharField(max_length=15)),
                ('nick_suffix', models.CharField(max_length=5)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collectibles.Location'),
        ),
        migrations.AddField(
            model_name='content',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collectibles.Location'),
        ),
        migrations.AddField(
            model_name='acquireditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectibles.Item'),
        ),
        migrations.AddField(
            model_name='acquireditem',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectibles.Location'),
        ),
        migrations.AddField(
            model_name='acquireditem',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectibles.Player'),
        ),
    ]
