# Generated by Django 2.1.1 on 2018-09-22 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('content_type', models.CharField(choices=[('URL', 'Url content'), ('IMG', 'Image'), ('INFO', 'Information')], max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QR_key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=124, unique=True)),
                ('location', models.TextField(max_length=124)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collectibles.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=64, unique=True)),
                ('nick', models.CharField(max_length=25)),
                ('items', models.ManyToManyField(to='collectibles.Item')),
            ],
        ),
    ]
