# Generated by Django 2.1.1 on 2018-09-29 05:53

import collectibles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcquiredItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=50)),
                ('content_type', models.CharField(choices=[('URL', 'Url content'), ('IMG', 'Image'), ('INFO', 'Information')], max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('QR_key', models.CharField(default=collectibles.models.key_generator, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('nick', models.CharField(max_length=15)),
                ('nick_suffix', models.CharField(max_length=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collectibles.Location'),
        ),
        migrations.AddField(
            model_name='content',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collectibles.Location'),
        ),
        migrations.AddField(
            model_name='acquireditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectibles.Item'),
        ),
        migrations.AddField(
            model_name='acquireditem',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectibles.Player'),
        ),
    ]
