# Generated by Django 2.1.1 on 2018-10-02 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('URL', 'Url content'), ('YT', 'Youtube video'), ('IMG', 'Image'), ('INFO', 'Information')], max_length=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collectibles.Location'),
        ),
    ]
