# Generated by Django 2.1.1 on 2018-10-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0002_auto_20181002_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='icon_path',
            field=models.CharField(default='img/di.png', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
