# Generated by Django 2.1.1 on 2018-10-06 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0003_auto_20181005_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acquireditem',
            options={'ordering': ('acquired',)},
        ),
        migrations.RenameField(
            model_name='acquireditem',
            old_name='acquired_date',
            new_name='acquired',
        ),
        migrations.AddField(
            model_name='player',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='icon_path',
            field=models.CharField(default='img/di.png', max_length=150),
        ),
    ]
