# Generated by Django 2.1.1 on 2018-10-06 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0004_auto_20181006_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquireditem',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='collectibles.Location'),
            preserve_default=False,
        ),
    ]
