# Generated by Django 2.1.1 on 2018-10-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0005_acquireditem_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='img_path',
            field=models.CharField(default='img/locations/default.jpg', max_length=150),
        ),
        migrations.AddField(
            model_name='location',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('URL', 'Url content'), ('YT', 'Youtube video'), ('IMG', 'Image'), ('INFO', 'Information'), ('API', 'Rest API Call')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon_path',
            field=models.CharField(default='img/stickers/default.png', max_length=150),
        ),
    ]
