# Generated by Django 2.1.1 on 2018-10-10 01:49

import collectibles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0006_auto_20181009_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='QR_key',
            field=models.CharField(default=collectibles.models.key_generator, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
